import assert from 'node:assert/strict';
import { installTestRandomness } from './helpers/seededRandom.mjs';
installTestRandomness(20260923);
import { createServer } from 'vite';
const values = new Map();
let quotaLimit = Infinity;
globalThis.localStorage = { getItem: k => values.get(k) || null, setItem: (k,v) => { if (v.length * 2 > quotaLimit) { const e = new Error('Test storage quota'); e.name = 'QuotaExceededError'; throw e; } values.set(k,v); }, removeItem: k => values.delete(k) };
const server = await createServer({ server: { middlewareMode: true, hmr: false }, appType: 'custom' });
try {
    const { packCollege, unpackCollege } = await server.ssrLoadModule('/src/engine/franchiseSave.js');
    const { createStaff, coachingCarousel, staffBonuses } = await server.ssrLoadModule('/src/engine/franchiseStaff.js');
    const { createCollegePipeline, updateCollege, collegeDraftClass, nextCollegeYear } = await server.ssrLoadModule('/src/engine/collegePipeline.js');
    const { assistantPlan, ASSISTANT_DEFAULTS } = await server.ssrLoadModule('/src/engine/frontOfficeAssistant.js');
    const { TEAMS } = await server.ssrLoadModule('/src/data/teams.js');
    const { useGameStore: store } = await server.ssrLoadModule('/src/store/gameStore.js');
    const user = TEAMS[0].id, rival = TEAMS[1].id;
    const coaches = createStaff(TEAMS,2024,user,{name:'Test Coach'});
    const oc = coaches.find(c => c.teamId === user && c.role === 'OC'); oc.reputation = 99;
    const standings = Object.fromEntries(TEAMS.map(t => [t.id,{wins:8,losses:9}]));
    standings[user] = {wins:14,losses:3}; standings[rival] = {wins:3,losses:14};
    const firedId = coaches.find(c => c.teamId === rival && c.role === 'HC').id;
    const carousel = coachingCarousel(coaches,TEAMS,standings,user,2024);
    assert.equal(carousel.coaches.find(c => c.id === oc.id).role,'HC');
    assert.equal(carousel.coaches.find(c => c.id === oc.id).teamId,rival);
    assert.equal(carousel.coaches.find(c => c.id === oc.id).mentorId,`coach-${user}-HC`);
    assert.equal(carousel.coaches.find(c => c.id === firedId).history.some(h => h.event.startsWith('Fired')),true);
    for (const t of TEAMS.filter(t => t.id !== user)) for (const role of ['HC','OC','DC','Assistant']) assert.equal(carousel.coaches.filter(c => c.teamId === t.id && c.role === role).length,1);
    assert.equal(carousel.coaches.filter(c => c.teamId === user && c.role === 'OC').length,0,'poached user role stays vacant');
    const old = staffBonuses(coaches,user); oc.skills.offense = 1;
    assert.ok(staffBonuses(coaches,user).passingBoost > old.passingBoost);
    const roster = Array.from({length:53},(_,i) => ({id:`p${i}`,name:`Player ${i}`,position:i<3?'QB':'WR',ovr:i===0?95:68,age:25,contract:{salary:i===52?30:2,yearsLeft:1}}));
    assert.equal(assistantPlan(roster,ASSISTANT_DEFAULTS).actions.length,0,'default manual');
    const plan = assistantPlan(roster,{...ASSISTANT_DEFAULTS,contracts:true,cap:true,reserve:50,protectedIds:['p0','p52'],maxSalary:5});
    assert.ok(plan.actions.every(a => !['p0','p52'].includes(a.playerId)));
    assert.ok(plan.actions.filter(a => a.type==='extend').every(a => a.salary <= 5));
    assert.ok(plan.capAfter <= 150);
    const expensiveDepth = roster.map(p => ({ ...p, contract: { ...p.contract, salary: p.id === 'p52' ? 100 : 2 } }));
    const capPlan = assistantPlan(expensiveDepth,{...ASSISTANT_DEFAULTS,cap:true});
    assert.ok(capPlan.actions.some(a => a.type === 'release' && a.playerId === 'p52'));
    assert.ok(!capPlan.actions.some(a => a.playerId === 'p0'),'starter is retained');
    const blocked = assistantPlan(expensiveDepth,{...ASSISTANT_DEFAULTS,cap:true,protectedIds:['p52'],reserve:50});
    assert.ok(blocked.notices.length > 0); assert.ok(blocked.actions.length <= 7,'46-player floor');
    assert.ok(!blocked.actions.some(a => a.playerId === 'p52'));
    const pipeline = createCollegePipeline(2024);
    assert.deepEqual(unpackCollege(packCollege(pipeline)),pipeline,'college save compaction is lossless');
    assert.ok(JSON.stringify(packCollege(pipeline)).length < JSON.stringify(pipeline).length / 2);
    assert.equal(pipeline.length,1400); assert.equal(new Set(pipeline.map(p => p.id)).size,1400);
    assert.ok(pipeline.filter(p => p.tier==='Normal').length > 700);
    const freshman = pipeline.find(p => p.entryYear===2024);
    assert.ok(freshman.seasons.every(row => row.games===0));
    let growing = pipeline;
    for(let year=2024;year<=2027;year++) {
        growing = updateCollege(growing,year,18);
        assert.deepEqual(updateCollege(growing,year,18),growing,'college updates idempotent');
        if(year<2027) growing = nextCollegeYear(growing,year+1);
    }
    const cls = collegeDraftClass(growing,2028);
    const graduate = cls.find(p => p.id === freshman.id);
    assert.equal(graduate.name,freshman.name); assert.equal(graduate.collegeProfile.seasons.length,4);
    assert.equal(cls.length,350); assert.equal(new Set(cls.map(p => p.id)).size,350);
    assert.ok(graduate.collegeStory.length>=5);
    store.getState().generateLeague(); store.getState().selectTeam(user,{name:'Test Coach'});
    assert.equal(store.getState().collegePipeline.length,1400);
    quotaLimit = 5 * 1024 * 1024;
    for (let i = 0; i < 18; i++) store.getState().simulateWeek();
    await new Promise(resolve => setTimeout(resolve,350));
    const savedSeason = [...values.values()].map(v => { try { return JSON.parse(v); } catch { return null; } }).find(v => unpackCollege(v?.collegePipeline)?.length === 1400 && v?.schedule?.some(week => week.some(g => g.played)));
    assert.ok(savedSeason, 'one full season with college and coaching fits controlled 5MiB UTF-16 save quota');
    assert.equal(unpackCollege(savedSeason.collegePipeline).find(p => p.draftYear === 2025).seasons.at(-1).games >= 10,true);
    quotaLimit = Infinity;
    const candidate = store.getState().coachingStaff.find(c => !c.teamId);
    assert.equal(store.getState().hireStaff(candidate.id,'OC').ok,false,'occupied role refuses hire');
    const incumbent = store.getState().coachingStaff.find(c => c.teamId===user && c.role==='OC');
    store.getState().fireStaff(incumbent.id);
    assert.equal(store.getState().hireStaff(candidate.id,'OC').ok,true);
    assert.equal(store.getState().hireStaff(candidate.id,'DC').ok,false);
    store.getState().upgradeStaff(candidate.id,'defense');
    assert.equal(store.getState().coachingStaff.find(c=>c.id===candidate.id).skills.defense,1);
    store.getState().upgradeStaff(candidate.id,'defense');
    assert.equal(store.getState().coachingStaff.find(c=>c.id===candidate.id).skills.defense,1,'no free skill points');
    const watched = store.getState().collegePipeline.find(p => p.draftYear===2025);
    store.getState().toggleCollegeWatch(watched.id);
    store.setState({phase:'playoffs',standings});
    store.getState().startOffseason();
    store.getState().startFreeAgency(); store.getState().generateDraftPreview();
    assert.equal(store.getState().draftClass.find(p=>p.id===watched.id).name,watched.name);
    assert.equal(store.getState().draftClass.find(p=>p.id===watched.id).collegeProfile.seasons.at(-1).year,2024);
    assert.ok(store.getState().draftClass.every(p => p.collegeProfile.seasons.every(row => Object.values(row).every(v => typeof v !== 'object'))), 'draft resume cells must be renderable scalars');
    store.getState().startDraft();
    while (store.getState().currentPickIndex < 224) {
        const state = store.getState();
        if (state.onClockTeamId === user) state.makePick(state.draftClass[0].id); else state.simOneCpuPick();
    }
    store.getState().finalizeDraft();
    // CLAUDE: early declarations move ~25-40 juniors into the draft a year early.
    assert.ok(store.getState().collegePipeline.length >= 1300 && store.getState().collegePipeline.length <= 1400, `pipeline ${store.getState().collegePipeline.length}`);
    assert.equal(store.getState().collegeAlumni.find(p => p.id === watched.id).name,watched.name);
    assert.equal(store.getState().collegeAlumni.find(p => p.id === watched.id).seasons.length,4);
    assert.ok(!store.getState().collegePipeline.some(p => p.id===watched.id));
    store.getState().finalizeDraft(); assert.equal(store.getState().year,2025,'draft finalization runs once');
    store.getState().setAssistantSettings({contracts:true, reserve:20, maxSalary:50});
    store.getState().runAssistants();
    const afterAssistants = JSON.stringify(store.getState().rosters[user]);
    store.getState().runAssistants();
    assert.equal(JSON.stringify(store.getState().rosters[user]),afterAssistants,'repeated assistant execution does not renew the same deals');
    // A real save flush and a fresh store module must hydrate the new systems.
    await new Promise(resolve => setTimeout(resolve,350));
    const { useGameStore: reloaded } = await server.ssrLoadModule('/src/store/gameStore.js?franchise-reload');
    assert.equal(reloaded.getState().year,2025);
    assert.equal(reloaded.getState().assistantSettings.contracts,true);
    assert.equal(reloaded.getState().assistantSettings.reserve,20);
    assert.equal(reloaded.getState().collegeAlumni[0].id,watched.id);
    assert.equal(reloaded.getState().coachingStaff.find(c => c.id===candidate.id).history.length,store.getState().coachingStaff.find(c => c.id===candidate.id).history.length);
    const snapshot = JSON.stringify({coachingStaff:store.getState().coachingStaff,collegePipeline:store.getState().collegePipeline,assistantSettings:store.getState().assistantSettings});
    const parsed = JSON.parse(snapshot);
    assert.equal(parsed.collegePipeline.length,store.getState().collegePipeline.length); assert.equal(parsed.coachingStaff.length,store.getState().coachingStaff.length);
    // Existing saves acquire missing systems without replacing the franchise.
    store.setState({coachingStaff:[],collegePipeline:[],year:2035}); store.getState().ensureFranchiseSystems();
    assert.equal(store.getState().collegePipeline[0].draftYear,2036);
    assert.equal(store.getState().userTeamId,user);
    console.log('PASS: optional delegation, protection and spending limits; CPU firings, poaching, vacancies and staff skills; four-year college identity/history, draft handoff and old-save initialization.');
} finally { await server.close(); }
