import assert from 'node:assert/strict';
import { rivalryFor, rivalryGames, topRivals } from '../src/engine/rivalries.js';
const game = (homeScore, awayScore) => ({ played: true, homeTeamId: 'bills', awayTeamId: 'dolphins', homeScore, awayScore });
assert.equal(rivalryFor('bills', 'dolphins').level, 1);
assert.equal(rivalryFor('bills', 'cowboys').level, 0);
assert.equal(rivalryFor(null, 'bills').level, 0);
const schedule = [[game(24, 21), { ...game(null, null), played: false }]];
const playoffBracket = { afc: { div: [game(21, 28)] } };
const rows = rivalryGames(schedule, playoffBracket);
assert.equal(rows.length, 2);
const live = { year: 2024, schedule, playoffBracket };
assert.deepEqual(rivalryFor('bills', 'dolphins', live).h2h, { wins: 1, losses: 1, ties: 0 });
assert.equal(rivalryFor('bills', 'dolphins', live).level, 3);
const archived = { ...live, seasonHistory: [{ year: 2024, rivalryGames: rows }] };
assert.deepEqual(rivalryFor('bills', 'dolphins', archived), rivalryFor('bills', 'dolphins', live));
const next = { year: 2025, schedule: [[game(10, 10)]], seasonHistory: archived.seasonHistory };
assert.deepEqual(rivalryFor('dolphins', 'bills', next).h2h, { wins: 1, losses: 1, ties: 1 });
assert.equal(topRivals('bills', next)[0].teamId, 'dolphins');
assert.equal(topRivals('bills', {}, 0).length, 0);
assert.deepEqual(rivalryFor('bills', 'cowboys', {seasonHistory: [{seasonRecap: {winner:'bills',finalist:'cowboys'}}]}).h2h, {wins:1, losses:0,ties:0});
assert.equal(rivalryFor('bills', 'cowboys', {seasonHistory: [{seasonRecap: {winner:'bills',finalist:'cowboys'}}]}).reasons.some(r=>r.includes('one-score')), false);
console.log('PASS: rivalries, historical H2H, playoff heat, legacy saves, archive deduplication.');
